version: '3'
services:
    redis:
        container_name: enpii_dev_suite_redis
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis:/data # Remember to replace `./data` with your actual data folder
        restart: always
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
        container_name: enpii_dev_suite_elasticsearch
        ports: ['9200:9200']
        volumes:
          - './data/elasticsearch:/usr/share/elasticsearch/data' # Remember to replace `./data` with your actual data folder
    nginx:
        image: nginx:alpine
        container_name: enpii_dev_suite_nginx_main
        volumes:
            - "./etc/nginx:/etc/nginx/conf.d"
            - "./etc/ssl:/etc/ssl"
            - "./www:/var/www/html" # Remember to replace `./www` with your actual www folder. Setting A, this setting must be same as setting B.
        ports:
            - "80:80"
            - "443:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.conf.example > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
    php7_2_15:
        image: nanoninja/php-fpm:7.2.15
        container_name: enpii_dev_suite_php72
        restart: always
        volumes:
            - "./scripts/php/install-tools.sh:/root/install-tools.sh" # chmod +x /root/install-tools.sh && /root/install-tools.sh
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf"
            - "./etc/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
            - "./www:/var/www/html" # # Remember to replace `./www` with your actual data folder. Setting B, this setting must be same as setting A.
