version: "3.6"
networks:
  enpii_dev_suite:
    name: enpii_dev_suite_default
services:
  nginx_main:
    build:
      args:
        NGINX_VERSION: ${NGINX_VERSION}
      context: "${DEV_SUITE_BASE}/build/nginx"
    container_name: enpii_dev_suite_nginx_main
    volumes:
      - "./scripts:/scripts"
      - "./etc/nginx:/etc/nginx/conf.d"
      - "./etc/ssl:/etc/ssl"
      - "${WWW_DIR}:/var/www/html"
      - "${NGINX_LOG_DIR}:/var/log/nginx"
    ports:
      - "${NGINX_HTTP_EXPOSING_PORT}:80"
      - "${NGINX_HTTPS_EXPOSING_PORT}:443"
    environment:
      NGINX_HOST:
    networks:
      - enpii_dev_suite
    depends_on:
      - php72_fpm
  php72_fpm:
    build:
      context: "${DEV_SUITE_BASE}/build/php72-fpm"
    container_name: enpii_dev_suite_php72_fpm
    volumes:
      - "${WWW_DIR}:/var/www/html"
    environment:
      - PHP_UPLOAD_MAX_FILEZISE
      - PHP_POST_MAX_SIZE
      - PHP_MEMORY_LIMIT
      - PHP_MAX_EXECUTION_TIME
      - PHP_MAX_INPUT_TIME
    networks:
      - enpii_dev_suite
  php72_cli:
    build:
      context: "${DEV_SUITE_BASE}/build/php72-cli"
    container_name: enpii_dev_suite_php72_cli
    networks:
      - enpii_dev_suite
  #    php74_fpm:
  #        build:
  #            context: "${DEV_SUITE_BASE}/build/php74-fpm"
  #        container_name: enpii_dev_suite_php74_fpm
  #        volumes:
  #            - "${WWW_DIR}:/var/www/html"
  #        environment:
  #            - PHP_UPLOAD_MAX_FILEZISE
  #            - PHP_POST_MAX_SIZE
  #            - PHP_MEMORY_LIMIT
  #            - PHP_MAX_EXECUTION_TIME
  #            - PHP_MAX_INPUT_TIME
  #        networks:
  #            - enpii_dev_suite
  #    php74_cli:
  #        build:
  #            context: "${DEV_SUITE_BASE}/build/php74-cli"
  #        container_name: enpii_dev_suite_php74_cli
  #        networks:
  #            - enpii_dev_suite
  mysql57:
    build:
      context: "${DEV_SUITE_BASE}/build/mysql57"
    container_name: enpii_dev_suite_mysql57
    environment:
      - MYSQL_DATABASE=${MYSQL57_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL57_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL57_USER}
      - MYSQL_PASSWORD=${MYSQL57_PASSWORD}
    volumes:
      - type: volume
        source: mysql57-data
        target: /var/lib/mysql
    ports:
      - "${MYSQL57_EXPOSING_PORT}:3306"
    networks:
      - enpii_dev_suite
  mysql57_slave:
    build:
      context: "${DEV_SUITE_BASE}/build/mysql57"
    container_name: enpii_dev_suite_mysql57_slave
    environment:
      - MYSQL_DATABASE=${MYSQL57_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL57_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL57_SLAVE_USER}
      - MYSQL_PASSWORD=${MYSQL57_SLAVE_PASSWORD}
    ports:
      - "${MYSQL57_SLAVE_EXPOSING_PORT}:3306"
    networks:
      - enpii_dev_suite
  #    mysql80:
  #        build:
  #            context: "${DEV_SUITE_BASE}/build/mysql80"
  #        container_name: enpii_dev_suite_mysql80
  #        environment:
  #            - MYSQL_DATABASE=${MYSQL80_DATABASE}
  #            - MYSQL_ROOT_PASSWORD=${MYSQL80_ROOT_PASSWORD}
  #            - MYSQL_USER=${MYSQL80_USER}
  #            - MYSQL_PASSWORD=${MYSQL80_PASSWORD}
  #        volumes:
  #            - type: volume
  #              source: mysql80-data
  #              target: /var/lib/mysql
  #        ports:
  #            - "${MYSQL80_EXPOSING_PORT}:3306"
  #        networks:
  #            - enpii_dev_suite
  #    mysql80_slave:
  #        build:
  #            context: "${DEV_SUITE_BASE}/build/mysql80"
  #        container_name: enpii_dev_suite_mysql80_slave
  #        environment:
  #            - MYSQL_DATABASE=${MYSQL80_DATABASE}
  #            - MYSQL_ROOT_PASSWORD=${MYSQL80_ROOT_PASSWORD}
  #            - MYSQL_USER=${MYSQL80_USER}
  #            - MYSQL_PASSWORD=${MYSQL80_PASSWORD}
  #        ports:
  #            - "${MYSQL80_SLAVE_EXPOSING_PORT}:3306"
  #        networks:
  #            - enpii_dev_suite
  phpmyadmin:
    build:
      context: "./build/phpmyadmin"
    container_name: enpii_dev_suite_phpmyadmin
    ports:
      - "${PHPMYADMIN_WEB_EXPOSING_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - enpii_dev_suite
#    phpmyadmin_slave:
#        build:
#            context: "./build/phpmyadmin"
#        container_name: enpii_dev_suite_phpmyadmin_slave
#        ports:
#            - "${PHPMYADMIN_SLAVE_WEB_EXPOSING_PORT}:80"
#        environment:
#            - PMA_ARBITRARY=1
#        networks:
#            - enpii_dev_suite
volumes:
  mysql57-data:
    driver: local
  mysql80-data:
    driver: local
